[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/dirtonly"
  to = "/dirtonly/"
  status = 301

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
